name: Sync Docs

on:
    # 允许手动push触发
    push:
        branches:
            - master
    # 允许外部仓库事件触发
    repository_dispatch:
        types:
            - deploy

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: 检查分支
              uses: actions/checkout@master

            - name: 安装node环境
              uses: actions/setup-node@master
              with:
                  node-version: "16.x"

            - name: 安装依赖
              run: |
                  export TZ='Asia/Shanghai'
                  npm install --prod

            - name: 拉取文档
              env:
                  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
                  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
                  HALO_ENDPOINT: ${{ secrets.HALO_ENDPOINT }}
                  HALO_TOKEN: ${{ secrets.HALO_TOKEN }}
                  HALO_POLICY_NAME: ${{ secrets.HALO_POLICY_NAME }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ELOG_GITHUB_USER: ${{ secrets.ELOG_GITHUB_USER }}
                  ELOG_GITHUB_REPO: ${{ secrets.ELOG_GITHUB_REPO }}
              run: |
                  npm run sync:halo

            - name: 配置Git用户名邮箱
              run: |
                  git config --global user.name "EmccK"
                  git config --global user.email "wangkai9799@gmail.com"

            - name: 提交拉取的文档到GitHub仓库
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt
                  git add .
                  git commit -m "Refresh elog.cache.json" -a
                  git push
